python3Packages.sse-starlette: add missing dependency, fix cross
fixes `nix-build -A pkgsCross.aarch64-multiplatform.python3Packages.sse-starlette`,
which would previously fail:

> Checking runtime dependencies for sse_starlette-3.2.0-py3-none-any.whl
>   - starlette not installed

In fact, non-cross builds would fail at runtime:

```
$ nix-build --expr 'with import ./. {}; python3.withPackages (ps: [ ps.sse-starlette])'
/nix/store/jbyj7s1axk7lb1vfgz3xsymyvw7lj1mc-python3-3.13.13-env
$ ./result/bin/python
>>> import sse_starlette
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import sse_starlette
  File "/nix/store/6v6l4jwpgy2zgd1cwnrgcm2mxlaxiyka-python3-3.13.13-env/lib/python3.13/site-packages/sse_starlette/__init__.py", line 2, in <module>
    from sse_starlette.sse import EventSourceResponse
  File "/nix/store/6v6l4jwpgy2zgd1cwnrgcm2mxlaxiyka-python3-3.13.13-env/lib/python3.13/site-packages/sse_starlette/sse.py", line 21, in <module>
    from starlette.background import BackgroundTask
ModuleNotFoundError: No module named 'starlette'
```